spring:
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  application:
    name: ai-code-parent
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ai_code?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: localhost
      ttl: 3600
server:
  port: 8300
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.szb.aicode.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
langchain4j:
  open-ai:
    chat-model:
      api-key: 'sk-c97d2f988a7940fa9bcc86e621138732'
      model-name: 'deepseek-chat'
      base-url: 'https://api.deepseek.com'
      log-requests: true
      log-responses: true
#      response-format: json_object
#      strict-json-schema: true
      max-tokens: 8192
    streaming-chat-model:
      api-key: 'sk-c97d2f988a7940fa9bcc86e621138732'
      model-name: 'deepseek-chat'
      base-url: 'https://api.deepseek.com'
      log-requests: true
      log-responses: true
      max-tokens: 8192
#  community:
#    redis:
#      port: 6379
#      host: localhost
cos:
  client:
    host: 'https://ai-code-1475684616.cos.ap-beijing.myqcloud.com'
    secretId: AKIDWt57wa186zkLn5FH6iAQTJwNcfVzMbif
    secretKey: nPsAKI5hAg7hCk9QdgYFkAWi0CHF4hA0
    region: ap-beijing
    bucket: ai-code-1475684616